Uncategoried: \\acepc-gk3\BUFFALO_Exp\recorded
Destination: \\acepc-gk3\Seagate 8T\categorized_mp4
Cache: ~/Desktop/workingFolder2
EPGStation: http://acepc-gk3.local:8888
Path:
  TsSplitter: C:\Software\TsSplitter
  Caption2Ass: C:\Software\Caption2Ass
Encoder: h264_nvenc
Presets:
  drama:
    videoFilter: bwdif=0
    crf: 24
  drama720p:
    videoFilter: bwdif=0,scale=1280:720
    crf: 24
  anime:
    videoFilter: pullup,fps=24000/1001
    crf: 24
  anime720p:
    videoFilter: pullup,fps=24000/1001,scale=1280:720
    crf: 24
  anime480p:
    videoFilter: pullup,fps=24000/1001,scale=852:480
    crf: 24
