Uncategoried: \\acepc-gk3\BUFFALO_Exp\recorded
Destination: \\acepc-gk3\Seagate 8T\categorized_mp4
Cache: ~/Desktop/workingFolder2
EPGStation: http://acepc-gk3.local:8888
Path:
  TsSplitter: C:\Software\TsSplitter
  Caption2Ass: C:\Software\Caption2Ass
Encoder: h264_nvenc
